name: "Signed Commit Action"
description: "Creates a signed commit using GitHub GraphQL and optionally creates a PR"
author: "Aaron Robinson"

inputs:
  git_path:
    description: "Path used by git to add files"
    required: false
    default: "."
  pr_title:
    description: "Title for the PR (only required if creating a new PR)"
    required: false
  pr_body:
    description: "Body for the PR (only required if creating a new PR)"
    required: false
  github_token:
    description: "GitHub token with permissions to commit and create PRs"
    required: true
  terraform_github_token:
    description: "GitHub token used for operations against the remote repository"
    required: false
  remote_repository:
    description: "The remote repository organisation & name if the changes are to be pushed to a remote repository"
    required: false
  remote_repository_path:
    description: "Path to the remote repository's local git directory"
    required: false
  base_branch:
    description: "Base branch to create new branch from (default: main)"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Check for changes
      run: |
        echo "===== Check for changes ====="
        if [ -n "${{ inputs.remote_repository_path }}" ]; then
          cd "${{ inputs.remote_repository_path }}"
        fi
        git_path="${{ inputs.git_path }}"
        git status
        git diff
        git add "$git_path"
        changes=$(git diff --staged --name-only)

        if [ -z "$changes" ]; then
          echo "No changes detected."
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "changes=true" >> $GITHUB_ENV
          git diff --staged --name-only > changed_files.txt
          cat changed_files.txt
        fi
      shell: bash

    - name: Set GITHUB_TOKEN with fallback
      if: env.changes == 'true'
      run: |
        if [ -n "${{ inputs.github_token }}" ]; then
          echo "Using github_token input"
          echo "GITHUB_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
        elif [ -n "${TERRAFORM_GITHUB_TOKEN}" ]; then
          echo "Using TERRAFORM_GITHUB_TOKEN env var"
          echo "GITHUB_TOKEN=${TERRAFORM_GITHUB_TOKEN}" >> $GITHUB_ENV
        else
          echo "No GitHub token provided, exiting"
          exit 1
        fi
      shell: bash

    - name: Get latest commit SHA of base branch
      if: env.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        echo "===== Get latest commit SHA from GitHub API ====="
        if [ -n "${{ inputs.remote_repository_path }}" ]; then
          cd "${{ inputs.remote_repository_path }}"
          github_repo="${{ inputs.remote_repository }}"
        else
          github_repo="${GITHUB_REPOSITORY}"
        fi

        base_branch="${{ inputs.base_branch }}"
        echo "Base branch is '$base_branch'"

        response=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${github_repo}/git/refs/heads/${base_branch}")

        echo "GitHub API response: $response"

        commit_oid=$(echo "$response" | jq -r '.object.sha')

        if [ -z "$commit_oid" ] || [ "$commit_oid" = "null" ]; then
          echo "❌ Failed to fetch commit SHA for base branch '$base_branch'"
          exit 1
        fi

        echo "✅ Commit OID for base branch $base_branch: $commit_oid"
        echo "commit_oid=$commit_oid" >> $GITHUB_ENV
        echo "branch_name=$base_branch" >> $GITHUB_ENV
      shell: bash

    - name: Generate new branch (if not PR event)
      if: env.changes == 'true' && github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        echo "===== Generate new branch ====="
        if [ -n "${{ inputs.remote_repository_path }}" ]; then
          cd "${{ inputs.remote_repository_path }}"
        fi

        date=$(date +%Y_%m_%d_%H_%M)
        new_branch="signed_commit_$date"
        base_branch="${{ inputs.base_branch }}"

        echo "Creating new branch '$new_branch' from base branch '$base_branch'"

        # Checkout base branch and reset to known commit_oid
        git fetch origin $base_branch
        git checkout -b $new_branch $commit_oid

        if [ -n "${{ inputs.remote_repository }}" ]; then
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/${{ inputs.remote_repository }}.git"
        fi

        git push -u origin $new_branch
        echo "branch_name=$new_branch" >> $GITHUB_ENV
      shell: bash

    - name: Use current branch if on a PR
      if: env.changes == 'true' && github.event_name == 'pull_request'
      run: |
        echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
      shell: bash

    - name: Prepare the changes for GraphQL
      if: env.changes == 'true'
      run: |
        echo "===== Prepare the changes for GraphQL ====="
        if [ -n "${{ inputs.remote_repository_path }}" ]; then
          cd "${{ inputs.remote_repository_path }}"
        fi

        files_for_commit='{"additions": []}'

        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            base64_content=$(base64 < "$file" | tr -d '\n')
            files_for_commit=$(echo "$files_for_commit" | jq --arg path "$file" --arg content "$base64_content" \
              '.additions += [{ "path": $path, "contents": $content }]')
          fi
        done < changed_files.txt

        echo "$files_for_commit" > files_for_commit.json
      shell: bash

    - name: Create signed commit using GraphQL
      if: env.changes == 'true'
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        echo "===== Create signed commit using GraphQL ====="
        if [ -n "${{ inputs.remote_repository_path }}" ]; then
          cd "${{ inputs.remote_repository_path }}"
          github_repo="${{ inputs.remote_repository }}"
        else
          github_repo="${GITHUB_REPOSITORY}"
        fi

        commit_message="Automated signed commit update"

        jq -n \
          --arg repository "$github_repo" \
          --arg branch_name "$branch_name" \
          --arg commit_oid "$commit_oid" \
          --arg commit_message "$commit_message" \
          --slurpfile fileChanges files_for_commit.json \
          '{
            query: "mutation($input: CreateCommitOnBranchInput!) { createCommitOnBranch(input: $input) { commit { oid } } }",
            variables: {
              input: {
                branch: {
                  repositoryNameWithOwner: $repository,
                  branchName: $branch_name
                },
                message: {
                  headline: $commit_message
                },
                fileChanges: $fileChanges[0],
                expectedHeadOid: $commit_oid
              }
            }
          }' > mutation_payload.json

        RESPONSE=$(curl -s -X POST -H "Authorization: bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          --data @mutation_payload.json https://api.github.com/graphql)

        COMMIT_OID=$(echo "$RESPONSE" | jq -r ".data.createCommitOnBranch.commit.oid")

        if [ "$COMMIT_OID" != "null" ]; then
          echo "✅ Commit successfully created with OID: $COMMIT_OID"
        else
          echo "❌ Error creating commit: $RESPONSE"
          exit 1
        fi
      shell: bash

    - name: Set PR title and body
      if: env.changes == 'true' && github.event_name != 'pull_request'
      run: |
        echo "pr_title=${{ inputs.pr_title }}" >> $GITHUB_ENV
        echo "pr_body=${{ inputs.pr_body }}" >> $GITHUB_ENV
      shell: bash

    - name: Create a PR if not running on a PR
      if: env.changes == 'true' && github.event_name != 'pull_request'
      env:
        GH_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        echo "===== Create a PR if not running on a PR ====="

        repo_option=""
        if [ -n "${{ inputs.remote_repository }}" ]; then
          repo_option="--repo github.com/${{ inputs.remote_repository }}"
        fi

        pr_title="${pr_title:-Automated Signed Commit Update}"
        pr_body="${pr_body:-This PR was automatically created by a GitHub workflow to apply a signed commit update.}"

        gh pr create $repo_option \
          --base "${{ inputs.base_branch }}" \
          --head "${branch_name}" \
          --title "$pr_title" \
          --body "$pr_body"
      shell: bash
