name: Code Formatter
description: "Runs MegaLinter to format code and apply linting rules across the repository, and uploads SARIF reports to GitHub Security tab."
author: "Aaron Robinson"

on:
  workflow_call:
    inputs:
      flavor:
        required: false
        default: "full"
        type: string
      apply_fixes:
        required: false
        default: "all"
        type: string
      apply_fixes_event:
        required: false
        default: "all"
        type: string
      apply_fixes_mode:
        required: false
        default: "pull_request"
        type: string
      disable_errors:
        required: false
        default: "true"
        type: string
      email_reporter:
        required: false
        default: "false"
        type: string
      enable_linters:
        required: false
        default: "JSON_PRETTIER,YAML_PRETTIER,TERRAFORM_TERRAFORM_FMT,MARKDOWN_MARKDOWNLINT"
        type: string
      ignore_files:
        required: false
        default: ""
        type: string
      markdown_markdownlint_filter_regex_exclude:
        required: false
        default: ""
        type: string
      report_output_folder:
        required: false
        default: ""
        type: string
      validate_all_codebase:
        required: false
        default: "false"
        type: string
      yaml_prettier_filter_regex_exclude:
        required: false
        default: "(.github/*)"
        type: string

jobs:
  format-code:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run MegaLinter
        uses: oxsecurity/megalinter/flavors/${{ inputs.flavor }}@e08c2b05e3dbc40af4c23f41172ef1e068a7d651 # v8.8.0
        env:
          APPLY_FIXES: ${{ inputs.apply_fixes }}
          APPLY_FIXES_EVENT: ${{ inputs.apply_fixes_event }}
          APPLY_FIXES_MODE: ${{ inputs.apply_fixes_mode }}
          DISABLE_ERRORS: ${{ inputs.disable_errors }}
          EMAIL_REPORTER: ${{ inputs.email_reporter }}
          ENABLE_LINTERS: ${{ inputs.enable_linters }}
          FILES_TO_EXCLUDE: ${{ inputs.ignore_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: ${{ inputs.markdown_markdownlint_filter_regex_exclude }}
          REPORT_OUTPUT_FOLDER: ${{ inputs.report_output_folder }}
          REPORTERS: sarif
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase != '' && inputs.validate_all_codebase || (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main' && 'true' || 'false' }}
          YAML_PRETTIER_FILTER_REGEX_EXCLUDE: ${{ inputs.yaml_prettier_filter_regex_exclude }}

      - name: Archive MegaLinter Reports
        if: success() || failure()
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

      - name: Upload SARIF to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@cf7e9f23492505046de9a37830c3711dd0f25bb3 # v2.16.2
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
