# action.yml
name: "Terraform security scan"
description: "Scan your terraform code with security tools such as Checkov and TFLint. The action will comment on pull requests with the results of the scan if 'comment_on_pr' is set to true."
inputs:
  scan_type:
    description: "full = all tf folders, changed = tf changes, single = single folder"
    required: false
    default: "single"
  comment_on_pr:
    description: "Whether or not to comment on pull requests."
    required: false
    default: true
  terraform_working_dir:
    description: "Terraform working directory."
    required: false
    default: "."
  checkov_exclude:
    description: "Provide checks via , without space to exclude from run"
    required: false
  checkov_external_modules:
    description: "Allow checkov to download and scan external modules"
    required: false
    default: false
  tflint_exclude:
    description: "Provide checks via , without space to exclude from run"
    required: false
  tflint_config:
    description: 'Provide a specific config for this run (including the .hcl extension), see the "tflint-configs" folder for available configs'
    required: false
  tflint_call_module_type:
    description: "Select types of module to call. The following values are valid: all, local (default), none"
    required: false
    default: "local"
  main_branch_name:
    description: "The name of the main branch e.g. 'main', defaults to 'main'"
    required: false
    default: "main"

runs:
  using: "docker"
  image: "./Dockerfile"
branding:
  icon: "shield"
  color: "gray-dark"
