---
name: Code Quality

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

permissions: {}

jobs:
  code-quality:
    permissions:
      actions: read
      contents: write
      pull-requests: write
      security-events: write
    uses: ./.github/workflows/reusable-code-quality.yml
