name: "Format Code: ensure code formatting guidelines are met"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: write
  security-events: write  # needed for SARIF upload

jobs:
  format-code:
    uses: ministryofjustice/modernisation-platform-github-actions/format-code@main # main
    with:
      ignore_files: "README.md"

  sign-commit:
    name: Commit and Create/Update PR with Signed Commit if Changes are Found
    needs: format-code
    uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@main
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      pr_title: "GitHub Actions Code Formatter workflow"
      pr_body: "This pull request includes updates from the GitHub Actions Code Formatter workflow. Please review the changes and merge if everything looks good."
